fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\MyUser
  from_email:
    address: "example@example.com"
    sender_name: "example@example.com"